const items = [
    {
      id: 1,
      name: 'The Great Gatsby',
      author: 'F. Scott Fitzgerald',
      category: 'Fiction',
      cover: '/images/1.jpg',
      price: 10.99,
      description: "The Great Gatsby is a classic American novel set in the Roaring Twenties. The story follows the life of Jay Gatsby and his pursuit of the beautiful Daisy Buchanan. The novel explores themes of love, wealth, and the American Dream, as well as the darker side of human nature. Fitzgerald's rich prose and vivid characters make this a must-read for fans of literary fiction.",
    },
    {
      id: 2,
      name: 'To Kill a Mockingbird',
      author: 'Harper Lee',
      category: 'Fiction',
      cover: '/images/2.jpg',
      price: 12.99,
      description: "To Kill a Mockingbird is a coming-of-age story set in the American South during the 1930s. The novel follows young Scout Finch as she navigates the complexities of racial prejudice and social injustice in her small town. Told through the eyes of a child, this classic work of literature explores themes of morality, empathy, and the importance of standing up for what is right.",
    },
    {
      id: 3,
      name: 'Pride and Prejudice',
      author: 'Jane Austen',
      category: 'Fiction',
      cover: '/images/3.jpg',
      price: 9.99,
      description: "Pride and Prejudice is a beloved classic that tells the story of Elizabeth Bennet and Mr. Darcy as they navigate societal expectations and personal prejudices in Regency-era England. With its witty dialogue and unforgettable characters, this novel explores themes of love, reputation, and the importance of personal growth. A must-read for fans of romance and classic literature.",
    },
    {
      id: 4,
      name: 'The Lord of the Rings',
      author: 'J.R.R. Tolkien',
      category: 'Fiction',
      cover: '/images/4.jpg',
      price: 25.99,
      description: "The Lord of the Rings is an epic high-fantasy novel that tells the story of Frodo Baggins and his quest to destroy the One Ring. Set in the mythical world of Middle-earth, the novel follows Frodo and his companions as they face unimaginable dangers in their quest to save their world from the dark forces of Sauron. A timeless tale of adventure, friendship, and the triumph of good over evil.",
    },
    {
      id: 5,
      name: '1984',
      author: 'George Orwell',
      category: 'Fiction',
      cover: '/images/5.jpg',
      price: 11.99,
      description: "1984 is a dystopian novel set in a totalitarian society where the government, known as 'The Party,' exercises total control over every aspect of its citizens' lives. The story follows the life of Winston Smith, a low-ranking Party member who begins to question the regime and its leader, Big Brother. A chilling portrayal of a world where surveillance, censorship, and manipulation are the norm.",
    },  {
        id: 6,
        name: 'One Hundred Years of Solitude',
        author: 'Gabriel García Márquez',
        category: 'Fiction',
        cover: '/images/6.jpg',
        price: 14.99,
        description: "One Hundred Years of Solitude is a masterpiece of magical realism that tells the story of the Buendía family over the course of seven generations. Set in the mythical town of Macondo, the novel explores themes of love, solitude, and the passage of time. Rich with symbolism and unforgettable characters, this epic tale is a must-read for fans of literature and magical realism.",
      },
      {
        id: 7,
        name: 'The Diary of a Young Girl',
        author: 'Anne Frank',
        category: 'Non-fiction',
        cover: '/images/7.jpg',
        price: 8.99,
        description: "The Diary of a Young Girl is the personal account of Anne Frank, a Jewish teenager who went into hiding with her family during World War II to escape persecution by the Nazis. The diary, written between 1942 and 1944, is a powerful and moving portrayal of a young girl's life, hopes, and fears during a time of unimaginable hardship. This important work provides a firsthand account of the Holocaust and is a testament to the resilience of the human spirit.",
      },
      {
        id: 8,
        name: 'Moby-Dick',
        author: 'Herman Melville',
        category: 'Fiction',
        cover: '/images/8.jpg',
        price: 19.99,
        description: "Moby-Dick is a classic American novel that tells the story of Captain Ahab's obsessive quest to hunt down the elusive white whale, Moby Dick. The novel is both an exciting adventure tale and a complex exploration of themes such as fate, free will, and the nature of obsession. With its richly detailed characters and vivid prose, Moby-Dick is a must-read for fans of classic literature and maritime adventure.",
      },
      {
        id: 9,
        name: 'The Catcher in the Rye',
        author: 'J.D. Salinger',
        category: 'Fiction',
        cover: '/images/9.jpg',
        price: 10.49,
        description: "The Catcher in the Rye is a coming-of-age novel that follows the story of Holden Caulfield, a troubled teenager who has been expelled from his prep school. As he wanders through New York City, Holden grapples with his feelings of alienation, depression, and the phoniness of the adult world. Written in a unique, first-person narrative, this timeless work captures the challenges and complexities of adolescence and remains a classic of American literature.",
      },
      {
        id: 10,
        name: 'The Hitchhiker\'s Guide to the Galaxy',
        author: 'Douglas Adams',
        category: 'Fiction',
        cover: '/images/10.jpg',
        price: 7.99,
        description: "The Hitchhiker's Guide to the Galaxy is a wildly imaginative and satirical science fiction novel that follows the misadventures of hapless human Arthur Dent and his alien friend Ford Prefect. After Earth is demolished to make way for a hyperspace bypass, the duo embarks on a journey through space, encountering a colorful cast of characters and absurd situations. Filled with wit and humor, this novel is a must-read for fans of science fiction and comedy.",
      },
    ]
  export default items;
 